# Generated by Django 2.1.5 on 2019-07-17 18:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190620_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 17, 18, 41, 46, 264369, tzinfo=utc)),
        ),
    ]
